#ifndef POS_PROJECT_PARAMS_H
#define POS_PROJECT_PARAMS_H

#define SECOND_NANOSEC 1000000000L
#define BYTE_SIZE 8

#define TEST_SAMPLES_COUNT 500 * 1000
#define TEST_TRIALS_COUNT 1 * 100 * 1000
#define BLOCK_SIZE_BITS 64
#define BLOCK_SIZE_BYTES BLOCK_SIZE_BITS / BYTE_SIZE
#define KEY_SIZE_BITS 128
#define KEY_SIZE_BYTES KEY_SIZE_BITS / BYTE_SIZE

#endif //POS_PROJECT_PARAMS_H
